# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: CryptoTool.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    # Build the solution
    - name: Build
      run: dotnet build $env:Solution_Name --no-restore --configuration ${{ matrix.configuration }}

    # Run tests (if any test projects exist)
    - name: Test
      run: dotnet test $env:Solution_Name --no-build --configuration ${{ matrix.configuration }} --verbosity normal
      continue-on-error: true  # Continue even if no test projects are found

    # Publish the WinForms application
    - name: Publish WinForms App
      run: dotnet publish CryptoTool.Win\CryptoTool.Win.csproj --configuration ${{ matrix.configuration }} --output ./publish/CryptoTool.Win --self-contained false

    # Publish the Console App
    - name: Publish Console App
      run: dotnet publish CryptoTool.App\CryptoTool.App.csproj --configuration ${{ matrix.configuration }} --output ./publish/CryptoTool.App --self-contained false

    # Upload build artifacts
    - name: Upload WinForms build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CryptoTool-WinForms-${{ matrix.configuration }}
        path: ./publish/CryptoTool.Win

    - name: Upload Console App build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CryptoTool-Console-${{ matrix.configuration }}
        path: ./publish/CryptoTool.App
